// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itijgkayxyuhxnpyvkyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0aWpna2F5eHl1aHhucHl2a3lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5OTk1NTUsImV4cCI6MjA2NjU3NTU1NX0.UsVWDPzx-9zSCqBlkS8hxhbpmv5mJtmzUdZjSuItdv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);